# Generated by Django 5.2.5 on 2025-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('team_members', models.PositiveIntegerField(default=0)),
                ('happy_customers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
