# Generated by Django 5.2.5 on 2025-09-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
