# Generated by Django 5.2.5 on 2025-09-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='profession_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='profession_ru',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='profession_uz',
        ),
    ]
