# Generated by Django 5.2.5 on 2025-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_reviews_image_remove_reviews_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reviews/images/'),
        ),
    ]
