# Generated by Django 5.2.5 on 2025-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_slug'),
        ('team', '0003_alter_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='projects', to='team.teammember'),
        ),
    ]
