# Generated by Django 5.2.5 on 2025-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_technology_options'),
        ('technology', '__first__'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, to='technology.technology'),
        ),
    ]
