# Generated by Django 5.2.5 on 2025-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slag',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
