# Generated by Django 5.2.5 on 2025-09-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slag',
            new_name='slug',
        ),
    ]
