# Generated by Django 5.2.5 on 2025-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_slag_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='colors',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='services/3d_file/'),
        ),
    ]
