# Generated by Django 5.2.5 on 2025-08-21 09:36

import trix_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_tags_delete_blogtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=trix_editor.fields.TrixEditorField(),
        ),
    ]
