# Generated by Django 5.2.5 on 2025-08-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='summary',
        ),
    ]
