# Generated by Django 5.2.5 on 2025-09-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_uz', models.CharField(max_length=50, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True)),
                ('name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('first_name_uz', models.CharField(max_length=50, null=True)),
                ('first_name_ru', models.CharField(max_length=50, null=True)),
                ('first_name_en', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('last_name_uz', models.CharField(max_length=50, null=True)),
                ('last_name_ru', models.CharField(max_length=50, null=True)),
                ('last_name_en', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('bio_uz', models.TextField(blank=True, null=True)),
                ('bio_ru', models.TextField(blank=True, null=True)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='team.role')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
