# Generated by Django 5.2.5 on 2025-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ManyToManyField(related_name='team_members', to='team.role'),
        ),
    ]
