# Generated by Django 5.2.5 on 2025-09-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_teammember_role_teammember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
