# Generated by Django 5.2.5 on 2025-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_teammember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
