# Generated by Django 5.2.5 on 2025-09-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_teammember_slug_en_teammember_slug_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='slug_uz',
        ),
    ]
