# Generated by Django 5.2.5 on 2025-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_remove_teammember_slug_en_remove_teammember_slug_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='team.role'),
        ),
    ]
