# Generated by Django 5.2.5 on 2025-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.FileField(default=1, upload_to='technology/icons/'),
            preserve_default=False,
        ),
    ]
