# Generated by Django 5.2.5 on 2025-09-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_technology_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_uz',
        ),
    ]
